<a href="https://colab.research.google.com/github/krishik1/Backend_LLD_Sept23Morning/blob/master/Copy_of_Advanced_Numpy%2C_Pandas%2C_plotting_%3B_Lecture_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1. 📊 Introduction to Pandas**

Pandas is a powerful library for data manipulation and analysis in Python. It builds on top of <font color="greed">NumPy</font> and provides easy-to-use data structures and functions for handling structured data. 🚀

### **Why Use Pandas?**
1. **Real-World Relevance**: Pandas helps analyze large datasets efficiently, such as customer reviews, financial data, or restaurant data like our **Zomato Bangalore dataset**.  
2. **Core Strengths**:  
   - Data cleaning, preparation, and exploration.
   - Supports handling **missing data**.  
   - Integrates seamlessly with libraries like <font color="magenta">Matplotlib</font> and <font color="magenta">NumPy</font>.  




**Installing Pandas**
To install Pandas, use the following command:

In [ ]:
!pip install pandas

^C
Requirement already satisfied: pandas in c:\users\vijay\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vijay\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vijay\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vijay\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vijay\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vijay\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

## **2. Pandas Core Components: DataFrame & Series🧱**
#### <span style="color: red;"> Note - accoridng to the script, this came after loading the dataset, but I felt we should introduce the concept of series and dataframe first since they are the building blocks of pandas

A <font color="green">Series</font> is a one-dimensional labeled array that can hold any data type. Think of it as a **single column of data** in a table.

💡 **Key Features for Zomato Analysis**:
- Data is labeled using an **index** (e.g., restaurant names or IDs for easy lookup).
- Supports operations like indexing, slicing, and filtering (e.g., selecting restaurants with ratings above 4.0 or costs below ₹500).

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/065/850/original/download_%281%29.png?1708489343">

A <font color="skyblue">DataFrame</font> is a two-dimensional table with labeled rows and columns. It is the core structure in Pandas, ideal for tabular data like the Zomato dataset.

💡 **Key Features for Zomato Analysis**:
- Can hold data of different types (e.g., restaurant names as strings, ratings as floats, cost_for_two as integers).
- Labeled rows (**index**, e.g., restaurant IDs) and columns (e.g., cuisine, location).
- Provides tools for filtering (e.g., restaurants in a specific area), aggregating (e.g., average rating by cuisine), and transforming data (e.g., normalizing costs).

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/065/849/original/download.png?1708489323">

#### <span style="color: red;"> Creating Series from numpy arrays ( highlight that pandas is implemented using numpy)

In [ ]:
votes = np.array([120, 240, 150])
ratings = np.array([4.1, 4.5, 3.9])
restaurants = np.array(['R1', 'R2', 'R3'])

In [ ]:
votes_series = pd.Series(votes, index=['R1', 'R2', 'R3'], name='Votes')

In [ ]:
votes_series

R1    120
R2    240
R3    150
Name: Votes, dtype: int64

In [ ]:
ratings_series = pd.Series(ratings, index=['R1', 'R2', 'R3'], name='Ratings')

In [ ]:
ratings_series

R1    4.1
R2    4.5
R3    3.9
Name: Ratings, dtype: float64

#### <span style="color: red;"> Introduce how two series can be combined into a dataframe - also a chance to introduce how concat and axis work in pandas

In [ ]:
combined_df = pd.concat([votes_series,ratings_series],axis=1)

In [ ]:
combined_df

    Votes  Ratings
R1    120      4.1
R2    240      4.5
R3    150      3.9

### <span style="color: red;"> Showcase how a dataframe can be created using a dictionary.
### <span style="color: red;"> Note - this part is shifted to the beginning to avoid breaking the flow from our original dataset later on

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}
df = pd.DataFrame(data)

In [ ]:
df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9

## **3. Getting a feel of our dataset**

Let's load our Zomato Bangalore dataset.

In [ ]:
# Downloading and unziping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv .

--2024-12-19 04:34:30--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.164.173.117, 18.164.173.58, 18.164.173.18, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.164.173.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   209MB/s    in 0.3s

2024-12-19 04:34:30 (209 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: 'zomato_dataset.csv' and './zomato_dataset.csv' are the same file

In [ ]:
import pandas as pd

df = pd.read_csv('zomato_dataset.csv')

## <span style="color: red;"> Introduce head and tail as ways to get a quick glance at the data


To get a quick glance at the Zomato Bangalore dataset, we can use the `.head()` and `.tail()` methods. These functions help Zomato's data team understand the dataset's structure, such as column names and sample values, without loading the entire dataset.

In [ ]:
# What key attributes (e.g., name, rating, cost) do the first and last five restaurants in the
# Zomato Bangalore dataset reveal for performance analysis?

# Let's look at the first few rows to understand the structure
df.head()

,name,customer_id,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,Jalsa,10589,2025-07-01 18:06:00,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,Spice Elephant,6133,2025-06-19 10:04:00,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,4057,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,12784,2025-07-25 05:40:00,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,Grand Village,10736,2025-06-19 03:15:00,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df.tail()

,name,customer_id,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
23461,Wokanaka - The Casual Chinese Pitstop,2228,2025-07-01 20:43:00,https://www.zomato.com/bangalore/wokanaka-the-...,"502, 4th C Cross, HRBR Layout 2nd Block Extens...",Yes,Yes,4.1/5,223,+91 7673910002\r\n080 41640002,Kalyan Nagar,Casual Dining,"Lemonade, Manchurian, Vegetable Noodles, Frenc...","Asian, Chinese, Thai, Seafood, Momos",'500.0',"[('Rated 5.0', 'RATED\n We had ordered Medium...","['Manchow Chicken Soup', 'Floret Gobi Manchuri...",Delivery,Kammanahalli
23462,Khatta Meetha Teekha,12942,2025-07-22 05:12:00,https://www.zomato.com/bangalore/khatta-meetha...,"12, 60 Feet Road, Koramangala 6th Block, Banga...",Yes,No,4.3 /5,193,+91 7259911898\n080 41113350,Koramangala 6th Block,Quick Bites,"Gulab Jamun, Raita, Chaat, Chole, Soya Chaap, ...","Street Food, North Indian, Mithai, Chinese, Be...",'300.0',"[('Rated 5.0', 'RATED\n Finally ordered in fr...","['Dal Makhan Maar ki', 'Vegetable Pulao', 'Gar...",Delivery,Koramangala 7th Block
23463,Cafe D'hide,1990,2025-06-22 05:52:00,https://www.zomato.com/bangalore/cafe-dhide-ko...,"130, 1st Cross, Koramangala 5th Block, Bangalore",Yes,Yes,4.2 /5,876,+91 7204196666,Koramangala 5th Block,Cafe,"Pasta, Coffee, Buffalo Chicken Wings, Caesar S...","Cafe, American, Continental, Italian",'600.0',"[('Rated 5.0', ""RATED\n Cafe D'hide is so coz...","['Chicken A La Kiev', 'Pan Seared Sea Bass Fil...",Delivery,Koramangala 7th Block
23464,B.M.W - Bhookh Mitaane Wala,14087,2025-06-13 20:13:00,https://www.zomato.com/bangalore/b-m-w-bhookh-...,"1st Block Koramangala, HSR Layout 5th Sector, ...",Yes,No,3.7/5,502,+91 9035955192,Koramangala 1st Block,Delivery,"Butter Chicken, Pasta, Gulab Jamun, Rolls, Fru...","North Indian, South Indian, Chinese",'500.0',"[('Rated 5.0', 'RATED\n Superb taste at a ver...",[],Delivery,Koramangala 4th Block
23465,Ande Ka Funda,4096,2025-06-22 00:26:00,https://www.zomato.com/bangalore/ande-ka-funda...,"199, 2nd Cross, 7th Block, Koramangala 7th Blo...",No,No,3.7 /5,73,+91 9036264592,Koramangala 7th Block,Quick Bites,"Rolls, Aloo Paratha, Lassi, Bread Omelette","North Indian, Chinese, Rolls",'250.0',"[('Rated 4.0', 'RATED\n In Simple words we ca...",[],Dine-out,Koramangala 4th Block

- Use `.head()` to preview the top 5 rows of the dataset.
- Use `.head(n)` to preview the top n rows of the dataset.
- Use `.tail(n)` to preview the bottom n rows of the dataset.

Business Context for Zomato:

- Using .head() helps Zomato's team quickly identify key columns (e.g., restaurant_name, rating, cost_for_two) and spot sample data, such as top-rated restaurants in Bangalore.
- .tail() ensures the dataset is complete by checking the last entries, which might reveal data entry issues or trends in newer restaurant listings.
These previews are critical for initial data exploration, enabling Zomato to assess data quality before analyzing customer preferences or restaurant performance.

# Basic Operations in rows

We can explore or get a feel our ataset using loc and iloc as well


### **Slicing Rows**

Rows can be sliced using implicit or explicit indices. Pandas provides two key tools for slicing:

1. **`.iloc`**: Slicing based on implicit integer indices.
2. **`.loc`**: Slicing based on explicit indices.



**Slicing Rows with `.iloc`**

Use `.iloc` for row selection by integer position:

In [ ]:
df.iloc[0]   # Access the first row

name                                                                       Jalsa
customer_id                                                                10589
visit_time                                                   2025-07-01 18:06:00
url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
Name: 0, dtype: object

In [ ]:
df.iloc[1:4]

,name,customer_id,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,Spice Elephant,6133,2025-06-19 10:04:00,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,4057,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,12784,2025-07-25 05:40:00,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari

In [ ]:
# How can Zomato's data team sample every third restaurant from the second to ninth entry in the
# Bangalore dataset to explore a subset of restaurant data?
df.iloc[1:9:3]

,name,customer_id,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,Spice Elephant,6133,2025-06-19 10:04:00,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
4,Grand Village,10736,2025-06-19 03:15:00,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
7,Penthouse Cafe,7397,2025-07-01 15:38:00,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",'700.0',"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari

Zomato Business Context:

- Using .iloc[0] helps Zomato inspect the first restaurant in the dataset (e.g., to verify data like name, rating, or cost_for_two).

- Slicing with .iloc[1:4] allows quick checks of a small group of restaurants, useful for spot-checking data quality or trends in Bangalore.

- Non-consecutive slicing (e.g., .iloc[1:9:3]) enables sampling restaurants at intervals, aiding in exploratory analysis of diverse dataset segments.

### Quiz 1

Suppose Zomato wants to check data of restaurants at 2nd, 5th, and 8th positions in the dataset. Which slicing command correctly achieves this?
- A) `df.iloc[1:8:3]`
- B) `df.iloc[2:9:3]`
- C) `df.iloc[1:9:3]`
- D) `df.iloc[2:8:3]`


Correct Option : A

### **Understanding Index in a DataFrame**

Every row in a DataFrame has an **index**, which uniquely identifies the row.

Indexing is critical for:
1. Accessing specific rows.
2. Slicing multiple rows.
3. Efficient filtering and data manipulation.

💡 **Key Types of Indexing:**
1. **Implicit Index**: The default integer-based row indices (`0, 1, 2, ...`).
2. **Explicit Index**: Custom labels you assign to rows (e.g., names or IDs).

In [ ]:
# How can Zomato's data team set customer_id as the explicit index in the
# Bangalore dataset to facilitate quick lookups and analysis of specific restaurants?

df_explicit = df.set_index("customer_id")
df_explicit

,name,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
customer_id,,,,,,,,,,,,,,,,,,
10589,Jalsa,2025-07-01 18:06:00,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
6133,Spice Elephant,2025-06-19 10:04:00,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
4057,San Churro Cafe,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
12784,Addhuri Udupi Bhojana,2025-07-25 05:40:00,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
10736,Grand Village,2025-06-19 03:15:00,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,Wokanaka - The Casual Chinese Pitstop,2025-07-01 20:43:00,https://www.zomato.com/bangalore/wokanaka-the-...,"502, 4th C Cross, HRBR Layout 2nd Block Extens...",Yes,Yes,4.1/5,223,+91 7673910002\r\n080 41640002,Kalyan Nagar,Casual Dining,"Lemonade, Manchurian, Vegetable Noodles, Frenc...","Asian, Chinese, Thai, Seafood, Momos",'500.0',"[('Rated 5.0', 'RATED\n We had ordered Medium...","['Manchow Chicken Soup', 'Floret Gobi Manchuri...",Delivery,Kammanahalli
12942,Khatta Meetha Teekha,2025-07-22 05:12:00,https://www.zomato.com/bangalore/khatta-meetha...,"12, 60 Feet Road, Koramangala 6th Block, Banga...",Yes,No,4.3 /5,193,+91 7259911898\n080 41113350,Koramangala 6th Block,Quick Bites,"Gulab Jamun, Raita, Chaat, Chole, Soya Chaap, ...","Street Food, North Indian, Mithai, Chinese, Be...",'300.0',"[('Rated 5.0', 'RATED\n Finally ordered in fr...","['Dal Makhan Maar ki', 'Vegetable Pulao', 'Gar...",Delivery,Koramangala 7th Block
1990,Cafe D'hide,2025-06-22 05:52:00,https://www.zomato.com/bangalore/cafe-dhide-ko...,"130, 1st Cross, Koramangala 5th Block, Bangalore",Yes,Yes,4.2 /5,876,+91 7204196666,Koramangala 5th Block,Cafe,"Pasta, Coffee, Buffalo Chicken Wings, Caesar S...","Cafe, American, Continental, Italian",'600.0',"[('Rated 5.0', ""RATED\n Cafe D'hide is so coz...","['Chicken A La Kiev', 'Pan Seared Sea Bass Fil...",Delivery,Koramangala 7th Block
14087,B.M.W - Bhookh Mitaane Wala,2025-06-13 20:13:00,https://www.zomato.com/bangalore/b-m-w-bhookh-...,"1st Block Koramangala, HSR Layout 5th Sector, ...",Yes,No,3.7/5,502,+91 9035955192,Koramangala 1st Block,Delivery,"Butter Chicken, Pasta, Gulab Jamun, Rolls, Fru...","North Indian, South Indian, Chinese",'500.0',"[('Rated 5.0', 'RATED\n Superb taste at a ver...",[],Delivery,Koramangala 4th Block
4096,Ande Ka Funda,2025-06-22 00:26:00,https://www.zomato.com/bangalore/ande-ka-funda...,"199, 2nd Cross, 7th Block, Koramangala 7th Blo...",No,No,3.7 /5,73,+91 9036264592,Koramangala 7th Block,Quick Bites,"Rolls, Aloo Paratha, Lassi, Bread Omelette","North Indian, Chinese, Rolls",'250.0',"[('Rated 4.0', 'RATED\n In Simple words we ca...",[],Dine-out,Koramangala 4th Block

Zomato Business Context:

- Setting customer_id as the index allows Zomato’s data team to quickly access specific customers  for performance analysis, such as checking ratings or order counts.
- An explicit index simplifies filtering or grouping operations, like analyzing all restaurants in a chain across Bangalore, enhancing efficiency in recommendation algorithms or marketing campaigns.

## Quiz 2

What is the main difference between implicit index and explicit index in a Pandas DataFrame?

- A) Implicit index uses column values, explicit index always starts from 0
- B) Implicit index is integer-based (0,1,2,...), explicit index is custom labels like IDs
- C) Implicit index is slower to access, explicit index is faster in all cases
- D) Implicit index can only be used with .loc, explicit index can only be used with .iloc


Correct Option : B

# <span style="color: red;"> Use .loc to access rows based on index

In [ ]:
df_explicit.loc[4057]

,name,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
customer_id,,,,,,,,,,,,,,,,,,
4057,San Churro Cafe,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
4057,Donne Biriyani Mane,2025-07-04 11:33:00,https://www.zomato.com/bangalore/donne-biriyan...,"48, Triumph Towers, Church Street, Bangalore",Yes,No,3.5/5,62,+91 9343507688\r\n+91 9738905017,Church Street,Quick Bites,"Donne Biryani, Mutton Biryani","Biryani, Kebab",'400.0',"[('Rated 3.0', 'RATED\n Visited here after sh...",[],Dine-out,Brigade Road
4057,Healthie,2025-07-29 18:50:00,https://www.zomato.com/bangalore/healthie-kora...,"First Floor, First Cross, Besides Bosch, Koram...",Yes,No,3.9 /5,107,080 41202278\r\n+91 7829745705,Koramangala 7th Block,Delivery,"Chicken Grill, Sandwich","Healthy Food, Beverages",'600.0',"[('Rated 1.0', 'RATED\n Worst service took 1 ...","['Veg Burrito Bowl', 'Chicken Protein Bowl', '...",Delivery,Koramangala 5th Block
4057,Breakfast House,2025-07-01 11:12:00,https://www.zomato.com/bangalore/breakfast-hou...,"95, EPIP Zone, ITPL Main Road, Whitefield",No,No,3.6 /5,49,080 28413047\n+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",'300.0',"[('Rated 3.0', 'RATED\n I ate combo comprisin...",[],Dine-out,Whitefield

<span style="color: red;"> You can also select multiple indices using loc

In [ ]:
df_explicit.loc[[4057,4096]]

,name,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
customer_id,,,,,,,,,,,,,,,,,,
4057,San Churro Cafe,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
4057,Donne Biriyani Mane,2025-07-04 11:33:00,https://www.zomato.com/bangalore/donne-biriyan...,"48, Triumph Towers, Church Street, Bangalore",Yes,No,3.5/5,62,+91 9343507688\r\n+91 9738905017,Church Street,Quick Bites,"Donne Biryani, Mutton Biryani","Biryani, Kebab",'400.0',"[('Rated 3.0', 'RATED\n Visited here after sh...",[],Dine-out,Brigade Road
4057,Healthie,2025-07-29 18:50:00,https://www.zomato.com/bangalore/healthie-kora...,"First Floor, First Cross, Besides Bosch, Koram...",Yes,No,3.9 /5,107,080 41202278\r\n+91 7829745705,Koramangala 7th Block,Delivery,"Chicken Grill, Sandwich","Healthy Food, Beverages",'600.0',"[('Rated 1.0', 'RATED\n Worst service took 1 ...","['Veg Burrito Bowl', 'Chicken Protein Bowl', '...",Delivery,Koramangala 5th Block
4057,Breakfast House,2025-07-01 11:12:00,https://www.zomato.com/bangalore/breakfast-hou...,"95, EPIP Zone, ITPL Main Road, Whitefield",No,No,3.6 /5,49,080 28413047\n+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",'300.0',"[('Rated 3.0', 'RATED\n I ate combo comprisin...",[],Dine-out,Whitefield
4096,Bathinda Junction,2025-06-24 12:50:00,https://www.zomato.com/bangalore/bathinda-junc...,"36, 29th Main Road, Mahadeshwara Nagar, Stage ...",Yes,No,3.9/5,362,+91 9740701619,BTM,Casual Dining,"Lassi, Shikanji, Dal Makhani, Makke Ki Roti, B...",North Indian,'600.0',"[('Rated 4.0', 'RATED\n Such good Punjabi foo...",[],Dine-out,Bannerghatta Road
4096,Ande Ka Funda,2025-06-22 00:26:00,https://www.zomato.com/bangalore/ande-ka-funda...,"199, 2nd Cross, 7th Block, Koramangala 7th Blo...",No,No,3.7 /5,73,+91 9036264592,Koramangala 7th Block,Quick Bites,"Rolls, Aloo Paratha, Lassi, Bread Omelette","North Indian, Chinese, Rolls",'250.0',"[('Rated 4.0', 'RATED\n In Simple words we ca...",[],Dine-out,Koramangala 4th Block
4096,Ande Ka Funda,2025-06-22 00:26:00,https://www.zomato.com/bangalore/ande-ka-funda...,"199, 2nd Cross, 7th Block, Koramangala 7th Blo...",No,No,3.7 /5,73,+91 9036264592,Koramangala 7th Block,Quick Bites,"Rolls, Aloo Paratha, Lassi, Bread Omelette","North Indian, Chinese, Rolls",'250.0',"[('Rated 4.0', 'RATED\n In Simple words we ca...",[],Dine-out,Koramangala 4th Block

# You can also reset the index to get back the original df

In [ ]:
df_explicit.reset_index()

,customer_id,name,visit_time,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,10589,Jalsa,2025-07-01 18:06:00,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,6133,Spice Elephant,2025-06-19 10:04:00,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,4057,San Churro Cafe,2025-07-05 16:14:00,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,12784,Addhuri Udupi Bhojana,2025-07-25 05:40:00,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,10736,Grand Village,2025-06-19 03:15:00,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23461,2228,Wokanaka - The Casual Chinese Pitstop,2025-07-01 20:43:00,https://www.zomato.com/bangalore/wokanaka-the-...,"502, 4th C Cross, HRBR Layout 2nd Block Extens...",Yes,Yes,4.1/5,223,+91 7673910002\r\n080 41640002,Kalyan Nagar,Casual Dining,"Lemonade, Manchurian, Vegetable Noodles, Frenc...","Asian, Chinese, Thai, Seafood, Momos",'500.0',"[('Rated 5.0', 'RATED\n We had ordered Medium...","['Manchow Chicken Soup', 'Floret Gobi Manchuri...",Delivery,Kammanahalli
23462,12942,Khatta Meetha Teekha,2025-07-22 05:12:00,https://www.zomato.com/bangalore/khatta-meetha...,"12, 60 Feet Road, Koramangala 6th Block, Banga...",Yes,No,4.3 /5,193,+91 7259911898\n080 41113350,Koramangala 6th Block,Quick Bites,"Gulab Jamun, Raita, Chaat, Chole, Soya Chaap, ...","Street Food, North Indian, Mithai, Chinese, Be...",'300.0',"[('Rated 5.0', 'RATED\n Finally ordered in fr...","['Dal Makhan Maar ki', 'Vegetable Pulao', 'Gar...",Delivery,Koramangala 7th Block
23463,1990,Cafe D'hide,2025-06-22 05:52:00,https://www.zomato.com/bangalore/cafe-dhide-ko...,"130, 1st Cross, Koramangala 5th Block, Bangalore",Yes,Yes,4.2 /5,876,+91 7204196666,Koramangala 5th Block,Cafe,"Pasta, Coffee, Buffalo Chicken Wings, Caesar S...","Cafe, American, Continental, Italian",'600.0',"[('Rated 5.0', ""RATED\n Cafe D'hide is so coz...","['Chicken A La Kiev', 'Pan Seared Sea Bass Fil...",Delivery,Koramangala 7th Block
23464,14087,B.M.W - Bhookh Mitaane Wala,2025-06-13 20:13:00,https://www.zomato.com/bangalore/b-m-w-bhookh-...,"1st Block Koramangala, HSR Layout 5th Sector, ...",Yes,No,3.7/5,502,+91 9035955192,Koramangala 1st Block,Delivery,"Butter Chicken, Pasta, Gulab Jamun, Rolls, Fru...","North Indian, South Indian, Chinese",'500.0',"[('Rated 5.0', 'RATED\n Superb taste at a ver...",[],Delivery,Koramangala 4th Block
23465,4096,Ande Ka Funda,2025-06-22 00:26:00,https://www.zomato.com/bangalore/ande-ka-funda...,"199, 2nd Cross, 7th Block, Koramangala 7th Blo...",No,No,3.7 /5,73,+91 9036264592,Koramangala 7th Block,Quick Bites,"Rolls, Aloo Paratha, Lassi, Bread Omelette","North Indian, Chinese, Rolls",'250.0',"[('Rated 4.0', 'RATED\n In Simple words we ca...",[],Dine-out,Koramangala 4th Block

Zomato Business Context:

- Resetting the index to implicit integers (0, 1, 2, ...) simplifies row-based operations, such as slicing or iterating over restaurants, which is useful for Zomato’s data team when analyzing large datasets.
- Using drop=True prevents clutter from unnecessary columns (e.g., old restaurant names as index), keeping the dataset clean for tasks like generating reports or feeding data into recommendation algorithms.
- The inplace=True option optimizes memory usage by updating the DataFrame directly, crucial for handling large restaurant datasets efficiently in Zomato’s analytics pipeline.

We can drop the index altogether

In [ ]:
df_explicit.reset_index(drop=True)

# Introducing inplace

In [ ]:
df_explicit.reset_index(inplace=True)

## <span style="color: red;"> Introduce .info() as a way to understand what columns are there, how many non-nulls, datatypes, and memory usage

Q. How can Zomato's data team quickly inspect the structure, column names, data types, and missing values
of the Bangalore restaurant dataset to ensure its quality for analyzing restaurant performance and customer preferences?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23466 entries, 0 to 23465
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0.1                 23466 non-null  int64
 1   Unnamed: 0                   23466 non-null  int64
 2   name                         23466 non-null  object
 3   customer_id                  23466 non-null  int64
 4   visit_time                   23466 non-null  object
 5   url                          23466 non-null  object
 6   address                      23466 non-null  object
 7   online_order                 23466 non-null  object
 8   book_table                   23466 non-null  object
 9   rate                         23466 non-null  object
 10  votes                        23466 non-null  int64
 11  phone                        23466 non-null  object
 12  location                     23365 non-null  object
 13  rest_type                    23466 non-null  object
 14  dish_liked                   23466 non-null  object
 15  cuisines                     23466 non-null  object
 16  approx_cost(for two people)  23466 non-null  object
 17  reviews_list                 23466 non-null  object
 18  menu_item                    23466 non-null  object
 19  listed_in(type)              23466 non-null  object
 20  listed_in(city)              23466 non-null  object
dtypes: int64(4), object(17)
memory usage: 3.8+ MB

`df.info()` gives a list of columns with:

- **Name** of columns
- **How many non-null values (blank cells)** each column has - observe location has a few nulls which we will see how to handle later
- **Type of values** in each column - int, float, etc.

**By default**, it shows **Dtype** as `object` for anything other than **int or float**.

Zomato Business Context:

- Knowing which columns have missing values (e.g., incomplete rating data) helps Zomato prioritize data cleaning for accurate recommendations.

- Identifying data types ensures proper handling (e.g., cost_for_two as numeric for cost analysis or rating as float for averaging).

- Memory usage insights guide Zomato in optimizing large datasets for performance in their analytics pipeline.

## <span style="color: red;"> Introduce .describe() which can give a quick statistical view of the data

Q. How can Zomato's data team obtain a statistical summary of numerical columns like ratings or costs in the Bangalore restaurant dataset to identify trends in restaurant performance?

In [ ]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

<span style="color: red;"> Observe we are getting statistical info of only 1 column. Why? Because all other columns are in object form. We will need to typecast some of our columns to convert them into numeric forms

Zomato Business Context:

- .describe() reveals key metrics, such as the average rating or cost_for_two across Bangalore restaurants, helping Zomato identify top-performing restaurants or typical dining costs for user recommendations.
- It highlights outliers (e.g., restaurants with unusually high costs or low ratings), which can guide Zomato’s restaurant success team in offering targeted support to improve performance.
- If only a few columns appear in the output (e.g., rating but not cost_for_two), it indicates non-numeric columns (stored as object) may need typecasting to numeric for deeper analysis, such as calculating average costs or vote counts.
- These insights empower Zomato to optimize marketing campaigns, refine restaurant recommendations, or assist partners in adjusting pricing or improving service quality based on statistical trends



---

## **3.🔍 Basic Operations on Columns**

Columns in a Pandas DataFrame represent individual data features.

<span style="color: red;"> columns named approx_cost(for two people) and rating are in object type when they are supposed to be in float/int form

### **Accessing Columns**
You can access columns using:
- **Dot notation**: `df.column_name`  
- **Bracket notation**: `df["column_name"]`

Q. # How can Zomato's data team retrieve the approx_cost(for two people) column from the Bangalore restaurant dataset to study dining cost patterns?

In [ ]:
# Accessing columns
costs = df["approx_cost(for two people)"]  # Bracket notation
print(costs)

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: approx_cost(for two people), Length: 23193, dtype: object

In [ ]:
rating = df.rate  # Dot notation
print(rating)

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [ ]:
df[['approx_cost(for two people)', 'rate' ]]  #accessing multiple columns

      approx_cost(for two people)    rate
0                         '800.0'   4.1/5
1                         '800.0'   4.1/5
2                         '800.0'   3.8/5
3                         '300.0'   3.7/5
4                         '600.0'   3.8/5
...                           ...     ...
23188                    '1200.0'  3.8 /5
23189                    '2000.0'  3.9 /5
23190                    '1200.0'  2.8 /5
23191                     '800.0'  2.5 /5
23192                    '2500.0'  4.3 /5

[23193 rows x 2 columns]

Zomato Business Context:

- Accessing the approx_cost(for two people) column helps Zomato analyze pricing trends across Bangalore restaurants.
- The rate column provides customer satisfaction scores, essential for recommending top-rated spots.

## Quiz 3

Which of the following correctly accesses multiple columns including one with spaces?
- A) `df[['approx_cost(for two people)', 'rate']]`
- B) `df['approx_cost(for two people)', 'rate']`
- C) `df.approx_cost, df.rate`
- D) `df.loc['approx_cost(for two people)', 'rate']`



Correct Option : A

### **Renaming Columns**
Use the `df.rename()` function to rename columns.

### <span style="color: red;"> column named approx_cost(for two people) can be renamed to something shorter and rate can be renamed to rating

Q. # How can Zomato's data team rename the approx_cost(for two people), votes, and rate columns to cost_for_two,Total_Votes and Ratings in the Bangalore restaurant dataset to improve clarity for analysis?

In [ ]:
# Renaming columns
df = df.rename(columns={"approx_cost(for two people)":'cost_for_two',"votes": "Total_Votes", "rate": "Ratings"})

# Displaying renamed DataFrame
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

Zomato Business Context:

- Renaming approx_cost(for two people) to cost_for_two simplifies queries for pricing analysis, such as identifying affordable restaurants for Zomato users in Bangalore.

- Changing votes to Total_Votes clearly indicates customer engagement (number of reviews), aiding in ranking restaurant popularity.

- Renaming rate to Ratings ensures consistency for customer satisfaction metrics, making it easier to analyze and visualize restaurant performance for Zomato’s recommendation engine or marketing campaigns.

💡 **Key Point**: Rename ensures clarity, especially when column names are too short or unclear or have some formatting errors.



### **Adding a New Column**
Add a new column by assigning data to a new column name.

### <span style="color: red;"> lets transform ratings into required form

In [ ]:
# Adding a new column
df["only_rating"] = df["Ratings"].str[:-2]

# Displaying new column
df["only_rating"]

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: object

### <span style="color: red;"> As you can see, rating is still in object type. We need to convert it into float type

In [ ]:
df["only_rating"] = df["only_rating"].astype(float)

ValueError: could not convert string to float: 'N'

### <span style="color: red;"> It is failing because it looks like there is an 'N' in the ratings column which cannot be converted into float. What are our options?

<span style="color: red;"> Option 1

### <span style="color: red;"> Replacing certain values in object type columns

In [ ]:
df["only_rating"] = df["only_rating"].replace('N', np.nan)

In [ ]:
df["only_rating"] = df["only_rating"].astype(float)

<span style="color: red;"> It is now working

<span style="color: red;"> Option 2

## <span style="color: red;"> Use pd.to_numeric with errors='coerce'

<span style="color: red;"> pd.to_numeric converts a column into numeric type. errors = 'coerce' is a parameter that will force the operation and convert values it cannot handle into nulls

In [ ]:
df["only_rating"] = pd.to_numeric(df["only_rating"], errors='coerce')

In [ ]:
df["only_rating"]

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: float64

In [ ]:
df["cost_for_two"]

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: cost_for_two, Length: 23193, dtype: object

In [ ]:
df["cost_for_two"] = pd.to_numeric(df["cost_for_two"].str.strip("'\""), errors="coerce")

In [ ]:
df["cost_for_two"]

0         800.0
1         800.0
2         800.0
3         300.0
4         600.0
          ...
23188    1200.0
23189    2000.0
23190    1200.0
23191     800.0
23192    2500.0
Name: cost_for_two, Length: 23193, dtype: float64

In [ ]:
# Adding a new column
df['cost_for_one']  = df['cost_for_two'] / 2

# Displaying new column
df['cost_for_one']

0         400.0
1         400.0
2         400.0
3         150.0
4         300.0
          ...
23188     600.0
23189    1000.0
23190     600.0
23191     400.0
23192    1250.0
Name: cost_for_one, Length: 23193, dtype: float64

In [ ]:
df["is_good"] = df["only_rating"] > 4
df["is_good"]

0         True
1         True
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192     True
Name: is_good, Length: 23193, dtype: bool

# Working with Nulls

### <span style="color: red;"> Checking for number of nulls in a column

<span style="color: red;"> During type casting, we saw that some values may have been replaced with null. We may now be interested in seeing how many rows were affected. If a large % of rows are affected, it may require different handling strategies based on the domain

<span style="color: red;"> Narrative : How will nulls impact our analysis?
<span style="color: red;"> Incorrect analysis results leading to incorrect decision making

Q. How can Zomato's data team identify which restaurants in the Bangalore dataset have missing values in the only_rating column to assess data quality for rating-based analysis?

In [ ]:
df["only_rating"].isna()

0        False
1        False
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192    False
Name: only_rating, Length: 23193, dtype: bool

In [ ]:
# How can Zomato's data team calculate the total number of missing values in the only_rating column of the
# Bangalore restaurant dataset to evaluate the extent of incomplete rating data?

df["only_rating"].isna().sum()

np.int64(147)

In [ ]:
df["only_rating"].isna().sum() / len(df)

np.float64(0.006338119260121588)

<span style="color: red;"> Only 0.6% of the values are nulls. So, it may not be too big a cause for concern. However, let us say, we dont want any nulls. We can replace our nulls using .fillna() or drop our nulls using .dropna()

- Use `inplace=True` to modify the original DataFrame.

<font color="red">
<p><strong>Zomato Business Context</strong>:</p>
<ul>
<li>A low null percentage (0.6%) suggests the dataset is reliable for analyses like calculating average ratings by location or cuisine, ensuring Zomato’s recommendation engine operates effectively.</li>
<li>For the few restaurants with null ratings (likely new listings), Zomato can exclude them from performance metrics or impute values (e.g., using cuisine averages) to maintain data integrity.</li>
<li>If a higher percentage were null, Zomato might need to investigate data collection issues or adjust strategies, such as prioritizing reviews for new restaurants to reduce missing ratings.</li>
</ul>
<pre><code></code></pre></font>

## Quiz 4

What does the following command return?

`df["only_rating"].isna()`


- A) Count of missing values
- B) Boolean Series indicating missing values
- C) Only the rows without nulls
- D) Raises an error if any null exists


Correct option : B


<span style="color: red;">  We have a few options:
1. <span style="color: red;">  We can replace nulls with a selected value such as 0 or 1 or 5
2. <span style="color: red;">  We can replace nulls with mean or median of a particular column
3. <span style="color: red;">  We can drop nulls altogether by selecting columns

In [ ]:
# 1
df["only_rating"].fillna(1)

In [ ]:
# 2
df["only_rating"].fillna(np.mean(df["only_rating"]))

In [ ]:
# 3
df.dropna(subset=['only_rating'])

In [ ]:
# After making the decision, use inplace=True
df["only_rating"].fillna(np.mean(df["only_rating"]), inplace=True)

##  <span style="color: red;">Working with nulls in case of categorical columns

 <span style="color: red;"> We observed location has some nulls. We can fill that with some placeholder like "Unknown"

In [ ]:
df["location"].fillna("Unknown")

<span style="color: red;"> Another option is to take the mode value and replace with that

In [ ]:
mode_value = df["location"].mode()[0]
df["location"].fillna(mode_value, inplace=True)

We can also fill nulls in one column with nulls in another column

In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'name', 'customer_id', 'visit_time',
       'url', 'address', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

## <span style="color: red;"> Narrative - ask which is the best replacement for location - most will answer column - listed_in(city)

In [ ]:
df["location"].fillna(df["listed_in(city)"], inplace=True)

### **Deleting a Column**

Use `df.drop()` to delete one or more columns:
- Set `axis=1` to indicate column deletion.
- Use `inplace=True` to modify the original DataFrame.

Q.  How can Zomato's data team remove the Ratings column from the Bangalore restaurant
# dataset to streamline it for analysis, retaining only the cleaned only_rating column?

In [ ]:
# Deleting a column
df.drop("Ratings", axis=1, inplace=True)  # now we do not need the old ratings column

# Displaying updated DataFrame
df.head()

,url,address,name,online_order,book_table,Total_Votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,Total_Votes_by_1000,is_good
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,0.775,True
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,0.787,True
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,0.918,True
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,0.088,False
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,0.166,False

### **Unique Values in a Column**

The `df["column_name"].unique()` method lists unique values in a column.

### <span style="color: red;"> Narrative: you want to see which locations and number of unique locations these restaurants belong too.

In [ ]:
# Finding unique values in the 'location' column
unique_locations = df["location"].unique()
print(unique_locations)

['Banashankari' 'Basavanagudi' 'Jayanagar' 'Kumaraswamy Layout'
 'Rajarajeshwari Nagar' 'Mysore Road' 'Uttarahalli' 'South Bangalore'
 'Vijay Nagar' 'Bannerghatta Road' 'JP Nagar' 'BTM' 'Wilson Garden'
 'Koramangala 5th Block' 'Shanti Nagar' 'Richmond Road' 'City Market'
 'Bellandur' 'Sarjapur Road' 'Marathahalli' 'HSR' 'Old Airport Road'
 'Indiranagar' 'Koramangala 1st Block' 'East Bangalore' 'MG Road'
 'Brigade Road' 'Lavelle Road' 'Church Street' 'Ulsoor' 'Residency Road'
 'Shivajinagar' 'Infantry Road' 'St. Marks Road' 'Cunningham Road'
 'Race Course Road' 'Domlur' 'Koramangala 8th Block' 'Frazer Town'
 'Ejipura' 'Vasanth Nagar' 'Jeevan Bhima Nagar' 'Old Madras Road'
 'Commercial Street' 'Koramangala 6th Block' 'Majestic' 'Langford Town'
 'Koramangala 7th Block' 'Brookefield' 'Whitefield'
 'ITPL Main Road, Whitefield' 'Varthur Main Road, Whitefield'
 'Koramangala 2nd Block' 'Koramangala 3rd Block' 'Koramangala 4th Block'
 'Koramangala' 'Bommanahalli' 'Hosur Road' 'Seshadripuram'
 'Electronic City' 'Banaswadi' 'North Bangalore' 'RT Nagar' 'Kammanahalli'
 'Hennur' 'HBR Layout' 'Kalyan Nagar' 'Thippasandra' 'CV Raman Nagar'
 'Kaggadasapura' 'Kanakapura Road' 'Nagawara' 'Rammurthy Nagar'
 'Sankey Road' 'Central Bangalore' 'Malleshwaram' 'Sadashiv Nagar'
 'Basaveshwara Nagar' 'Rajajinagar' 'New BEL Road' 'West Bangalore'
 'Yeshwantpur' 'Sanjay Nagar' 'Sahakara Nagar' 'Jalahalli' 'Yelahanka'
 'Magadi Road' 'KR Puram']

The `df["column_name"].nunique()` method lists number of unique values in a column.

In [ ]:
number_of_unique_locations = df["location"].nunique()
print(number_of_unique_locations)

88

## Quiz 5

Which of the following commands will fail?

- A) `df.location.unique()`
- B) `df["location"].nunique()`
- C) `df["location"].unique().count() `
- D) `df["location"].value_counts()`


Correct option : A , C
 Reason: .unique() returns a NumPy array, which has no .count() method; using .count() directly on the array will fail.

### **Value Counts in a Column**

The `df["column_name"].value_counts()` method counts occurrences of each unique value.

### <span style="color: yellow;"> Narrative: you might want to find out which are the most popular locations that people order from/ dine in

In [ ]:
# How can Zomato's data team count the number of restaurants in each unique location in the
# Bangalore dataset to identify the most popular dining or ordering areas?


# Counting occurrences of each unique value
location_counts = df["location"].value_counts()
location_counts

location
Koramangala 5th Block    1783
BTM                      1456
Indiranagar              1350
HSR                      1162
Jayanagar                1037
                         ...
Kanakapura Road             2
West Bangalore              2
Yelahanka                   2
Magadi Road                 2
KR Puram                    1
Name: count, Length: 88, dtype: int64

Question: Which is the most ordered restaurant in the dataset?

In [ ]:
restaurant_order_counts = df["name"].value_counts()
restaurant_order_counts

name
Onesta               85
Empire Restaurant    69
KFC                  59
McDonald's           57
Pizza Hut            56
                     ..
Agraharam Meal        1
Fresh 'N' Grills      1
Coorg Diaries         1
Lassi Resto Cafe      1
Fujian Express        1
Name: count, Length: 3159, dtype: int64

Which type of listing (e.g., delivery, dine-out, etc.) is the most common?

In [ ]:
listing_counts = df['listed_in(type)'].value_counts()
listing_counts

listed_in(type)
Delivery              10625
Dine-out               8009
Desserts               1333
Cafes                  1047
Drinks & nightlife      890
Buffet                  762
Pubs and bars           527
Name: count, dtype: int64

Zomato Business Context:

- Location Counts: High counts for locations like Koramangala or Indiranagar indicate demand hotspots, allowing Zomato to allocate more delivery riders or target promotions in these areas.
- Restaurant Orders: Identifying the most ordered restaurants (e.g., a chain appearing frequently) helps Zomato prioritize partnerships, feature them in promotions, or include them in loyalty programs like Zomato Gold.
- Listing Types: A dominance of delivery listings suggests a preference for online orders, guiding Zomato to enhance delivery logistics or focus app features on delivery options over dine-out in Bangalore.



---

## **5. 🎯 Working with Both Rows and Columns**

When analyzing data, you often need to work with both rows and columns simultaneously. Pandas provides powerful tools for selecting, slicing, and filtering data across multiple axes.

💡 **Key Tools for Selection**:
1. **`.iloc`**: Select rows and columns by integer position.
2. **`.loc`**: Select rows and columns by labels.


### **Using `.iloc` for Rows and Columns**

The `.iloc` method allows you to:
1. Select specific rows and columns by their integer indices.
2. Slice rows and columns together.

#### Example: Selecting Specific Rows and Columns

In [ ]:
# Select the first two rows and the first two columns
df.iloc[0:2, 0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [ ]:
# Select the last two rows and the last column
df.iloc[-2:, -1]

23191    False
23192    False
Name: is_good, dtype: bool

## **2. Using `.iloc` to Modify Data <span style="color: red;">( Would want to use the same dataset instead of creating a new one)**

In [ ]:
# For restaurants R2 and R3 on Zomato, update their number of votes and
# ratings to reflect recent changes in customer engagement and feedback.
# How can we modify the DataFrame to apply these updates at once?


# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)

# Assigning new values to multiple rows and columns
sample_df.iloc[1:3, 1:3] = [[300, 4.7], [180, 4.2]]

print("DataFrame after modifying rows and columns:")
print(sample_df)

DataFrame after modifying rows and columns:
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

**3. Using `.loc` to Select Rows and Columns**

The `.loc` method allows you to:
- Filter rows based on conditions.
- Update specific rows and columns by labels.

### <span style="color: red;"> Narrative: Your manager/team want you to flag a few restaurants as 1, 0 or -1 based on customer/delivery partner feedback feedback

In [ ]:
# Zomato wants to mark all restaurants with an initial flag to track them for future analysis or promotions.
# How can we add a new column flag and set it to 1 for all restaurants in the DataFrame?

#create a new column to keep track of flags - initially set it as 1 for all restaurants
df['flag'] = 1

In [ ]:
df

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,...,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,...,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,...,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining",...,"Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,...,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,...,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining",...,"North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",...,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar",...,"Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar",...,"Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,...,Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

In [ ]:
# Setting 'Restaurant' as the index
df_explicit = df.set_index("name")

# Select specific rows ('R2' and 'R3') and specific columns ('Votes')
print(df_explicit.loc[["Jalsa", "Grand Village"], ["flag"]])
print("==="*10)

# Updating the 'Votes' for restaurant 'R2'
df_explicit.loc["Jalsa", "flag"] = 0
print("Updated DataFrame:")
df_explicit

               flag
name
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Grand Village     1
Grand Village     1
Grand Village     1
Grand Village     1
==============================
Updated DataFrame:

,url,address,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
name,,,,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,0
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

**4. Using `.loc` for Conditional Updates**

### <span style="color: yellow;"> Narrative: You also recieve information to flag restaurnts with ratings less than 3 as -1 and between 3 and 4 as 0

In [ ]:
# Zomato wants to identify underperforming restaurants with ratings below 3 and mark them for review.
# How can we update the flag column to -1 for all restaurants where only_rating is less than 3?

# Update 'Rating' for all restaurants with 'Votes' greater than 200
df_explicit.loc[df_explicit["only_rating"] < 3, "flag"] = -1

### ✂️ Combining DataFrames with `concat`

The `concat` function allows you to combine multiple DataFrames:
1. **Row-wise Concatenation**: Add rows from another DataFrame.
2. **Column-wise Concatenation**: Add new columns from another DataFrame.



**1. Row-wise Concatenation**

You can stack two DataFrames vertically to combine their rows:

In [ ]:
# How can Zomato's data team combine a new set of restaurant data (e.g.,
# new Bangalore restaurants) with the existing dataset to create a unified DataFrame for comprehensive analysis?


# Creating a second DataFrame
data2 = {
    "Restaurant": ["R5", "R6"],
    "Votes": [90, 110],
    "Rating": [3.8, 4.3]
}

df2 = pd.DataFrame(data2)

# Concatenating row-wise
combined_df = pd.concat([sample_df, df2], ignore_index=True)
print("Combined DataFrame (Row-wise):")
print(combined_df)

Combined DataFrame (Row-wise):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R5     90     3.8
5         R6    110     4.3

Zomato Business Context:

- Row-wise concatenation allows Zomato to append new restaurant data (e.g., newly onboarded restaurants in Bangalore) to the existing dataset, ensuring the dataset stays up-to-date for user recommendations.
- Using ignore_index=True creates a new numerical index, simplifying analysis by maintaining a clean, sequential order for all restaurants.
- This approach helps Zomato integrate data from multiple sources (e.g., new restaurant listings or partner updates), supporting comprehensive market analysis and personalized dining suggestions.

**2. Column-wise Concatenation**

You can stack DataFrames side-by-side to add new columns:

In [ ]:
# Creating a DataFrame with new columns
new_columns = {
    "Delivery Time (mins)": [30, 25, 35, 20, 40, 28]
}

df_new_cols = pd.DataFrame(new_columns)

# Concatenating column-wise
final_df = pd.concat([combined_df, df_new_cols], axis=1)
print("Final DataFrame (Column-wise):")
final_df

Final DataFrame (Column-wise):

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.1                    30
1         R2    300     4.7                    25
2         R3    180     4.2                    35
3         R4     80     4.0                    20
4         R5     90     3.8                    40
5         R6    110     4.3                    28

Zomato Business Context:

- Adding a Delivery Time (mins) column enhances the dataset by providing insights into delivery efficiency, a key factor for Zomato users choosing restaurants in Bangalore.
- Column-wise concatenation with axis=1 allows Zomato to integrate new data (e.g., delivery performance metrics) from external sources, such as logistics partners, into the existing restaurant dataset.
- This enriched dataset supports Zomato in optimizing delivery operations, prioritizing restaurants with faster delivery times for user recommendations, or identifying restaurants needing logistics improvements to enhance customer satisfaction.

### 📝 Practice Questions

1. **Using `.iloc`**, retrieve the first two rows and the last column.

In [ ]:
# 1. Using `.iloc` to retrieve first two rows and last column
sample_df.iloc[:2, -1]

0    4.1
1    4.7
Name: Rating, dtype: float64

2. **Using `.loc`**, update the 'Rating' for restaurants with votes below 150 to 4.0.

In [ ]:
# 2. Using `.loc` to update 'Rating' for restaurants with votes < 150
sample_df.loc[sample_df["Votes"] < 150, "Rating"] = 4.0
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

3. Add a new row to the DataFrame for a restaurant 'R7' with 100 votes and a rating of 3.7.

In [ ]:
# 3. Adding a new row
new_row = pd.DataFrame([["R7", 100, 3.7]], columns=sample_df.columns)
sample_df = pd.concat([sample_df, new_row], ignore_index=True)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R7    100     3.7

4. Concatenate two DataFrames:
   - One with restaurant data.
   - One with a column showing average delivery time.

In [ ]:
# 4. Concatenating two DataFrames
df_with_time = pd.DataFrame({"Delivery Time (mins)": [30, 40, 20, 35, 25]})
final_combined_df = pd.concat([sample_df, df_with_time], axis=1)
final_combined_df

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.0                    30
1         R2    300     4.7                    40
2         R3    180     4.2                    20
3         R4     80     4.0                    35
4         R7    100     3.7                    25

5. Find the updated 'Rating' for restaurants with votes greater than 200 after combining two DataFrames.

In [ ]:
# 5. Finding updated 'Rating' for restaurants with votes > 200
updated_ratings = final_combined_df.loc[final_combined_df["Votes"] > 200, "Rating"]
print(updated_ratings)

1    4.7
Name: Rating, dtype: float64



---

## **6. 🗑️ Handling Duplicate Records in a DataFrame** - <span style="color: red;"> I would showcase using the current dataset itself, instead of creating a new df. Creating story lines on removing duplicates is easy anyway

In real-world datasets, duplicate records are common and can affect analysis. Pandas provides simple methods to identify and remove duplicates efficiently.


### **Key Methods for Handling Duplicates**

### **1. Identifying Duplicate Rows with `df.duplicated()`**

The `df.duplicated()` method:
- Returns `True` for duplicate rows (excluding the first occurrence by default).
- You can customize its behavior using the `keep` parameter:
  - `keep='first'` (default): Marks all duplicates except the first occurrence.
  - `keep='last'`: Marks all duplicates except the last occurrence.
  - `keep=False`: Marks **all** duplicates as `True`.

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Identifying duplicate rows
print("Duplicate rows (keep='first'):")
print(sample_df.duplicated())  # Default behavior

Duplicate rows (keep='first'):
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
print("Duplicate rows (keep='last'):")
print(sample_df.duplicated(keep="last"))

Duplicate rows (keep='last'):
0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
print("Duplicate rows (keep=False):")
print(sample_df.duplicated(keep=False))

Duplicate rows (keep=False):
0     True
1     True
2    False
3     True
4    False
5     True
dtype: bool

**Key Points**
- **Default (`keep='first'`)**: Treats the first occurrence of a duplicate as unique.
- **`keep='last'`**: Treats the last occurrence of a duplicate as unique.
- **`keep=False`**: Marks all duplicates as `True`.

Zomato Business Context:

- Identifying duplicates ensures Zomato’s dataset accurately represents unique restaurants, preventing inflated metrics like total votes or skewed average ratings.
- For example, duplicate entries for a restaurant like “Cafe Coffee Day” could overstate its popularity, affecting recommendation algorithms or marketing decisions.
Checking duplicates helps Zomato maintain data integrity, ensuring reliable insights for user recommendations, restaurant rankings, or market coverage analysis in Bangalore.

### **2. Removing Duplicate Rows**

The `df.drop_duplicates()` method removes duplicate rows based on the specified conditions:
- By default, it keeps the first occurrence of each duplicate row.
- You can use the `keep` parameter to change this behavior.

In [ ]:
# Removing duplicates (keep='first')
df_no_duplicates_first = sample_df.drop_duplicates(keep="first")
print("DataFrame after removing duplicates (keep='first'):")
print(df_no_duplicates_first)

DataFrame after removing duplicates (keep='first'):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates (keep='last')
df_no_duplicates_last = sample_df.drop_duplicates(keep="last")
print("DataFrame after removing duplicates (keep='last'):")
print(df_no_duplicates_last)

DataFrame after removing duplicates (keep='last'):
  Restaurant  Votes  Rating
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Removing all duplicates (keep=False)
df_no_duplicates_all = sample_df.drop_duplicates(keep=False)
print("DataFrame after removing all duplicates (keep=False):")
print(df_no_duplicates_all)

DataFrame after removing all duplicates (keep=False):
  Restaurant  Votes  Rating
2         R3    150     3.9
4         R4     80     4.0

### **3. Removing Duplicates Based on Specific Columns**

Sometimes, you might want to check duplicates only for certain columns. Use the `subset` parameter in `df.drop_duplicates()` to specify the columns to consider for duplication.

- Use `subset` in `df.drop_duplicates()` to check duplicates for specific columns.

In [ ]:
# Removing duplicates based on the 'Votes' column
df_no_duplicates_subset = sample_df.drop_duplicates(subset=["Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Votes':")
print(df_no_duplicates_subset)

DataFrame after removing duplicates based on 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates based on 'Restaurant' and 'Votes'
df_no_duplicates_multi_subset = sample_df.drop_duplicates(subset=["Restaurant", "Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Restaurant' and 'Votes':")
print(df_no_duplicates_multi_subset)

DataFrame after removing duplicates based on 'Restaurant' and 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

Zomato Business Context:

- Removing duplicates based on Total_Votes ensures Zomato avoids overcounting restaurants with identical review counts, refining popularity metrics for user recommendations.
- Using subset=["name", "Total_Votes"] checks for restaurants with the same name and vote count, which could indicate erroneous duplicate entries (e.g., a chain listed twice in the same location), improving data quality for restaurant rankings.
- These operations help Zomato maintain a clean dataset, ensuring accurate insights for marketing campaigns, delivery logistics, or identifying top-performing restaurants in Bangalore.



---

## **7. 📊 Pandas Built-In Operations: Aggregate Functions**

In [ ]:
# Sum of votes
print("Total Votes:", df["Total_Votes"].sum())

Total Votes: 13940720

In [ ]:
# Count of ratings
print("Number of Ratings:", df["only_rating"].count())

Number of Ratings: 23193

In [ ]:
# Select relevant columns and preprocess
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].str.replace(',', '')
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].str.replace("'", '')
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(float)

In [ ]:
# Average cost for two
print("Average Cost for Two:", df["approx_cost(for two people)"].mean())

Average Cost for Two: 755.90436769715

### **Applying Aggregate Functions on Multiple Columns**

You can also apply aggregate functions across multiple columns using the `.agg()` method.

#### Example: Aggregating Across Columns

In [ ]:
# Aggregating multiple columns
aggregates = df[["Total_Votes", "approx_cost(for two people)"]].agg(["sum", "mean", "min", "max"])
print("Aggregates for Votes and Cost for Two:")
aggregates

Aggregates for Votes and Cost for Two:

       Total_Votes  approx_cost(for two people)
sum   1.394072e+07                 1.753169e+07
mean  6.010745e+02                 7.559044e+02
min   0.000000e+00                 4.000000e+01
max   1.683200e+04                 6.000000e+03

Zomato Business Context:

- Using .agg() on Total_Votes and approx_cost(for two people) reveals key metrics, such as total engagement (sum), average costs (mean), and cost range (min, max), helping Zomato identify market trends.

- For example, a high max cost could highlight premium restaurants for Zomato Gold promotions, while a low min cost could inform budget-friendly dining campaigns.

- These aggregates support strategic decisions, like optimizing restaurant recommendations, targeting marketing in high-engagement areas, or advising restaurant partners on pricing strategies in Bangalore.


---

## **8. 🔀 Sorting Values in Pandas**

### **Sorting by a Single Column**

In [ ]:
# Sorting rows by the "Votes" column in ascending order
sorted_votes_asc = sample_df.sort_values(by="Votes", ascending=True)
print("DataFrame sorted by Votes (ascending):")
print(sorted_votes_asc)

DataFrame sorted by Votes (ascending):
  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
5         R1    120     4.1
2         R3    150     3.9
1         R2    240     4.5
3         R2    240     4.5

In [ ]:
# Sorting rows by the "Votes" column in descending order
sorted_votes_desc = sample_df.sort_values(by="Votes", ascending=False)
print("DataFrame sorted by Votes (descending):")
print(sorted_votes_desc)

DataFrame sorted by Votes (descending):
  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0



### **Sorting by Multiple Columns**

**Example: Sorting by "Votes" and "Rating"**

You can sort rows based on multiple columns by passing a list of column names.

In [ ]:
# Sorting by Votes (descending) and then by Rating (ascending)
sorted_multi = sample_df.sort_values(by=["Votes", "Rating"], ascending=[False, True])
print("DataFrame sorted by Votes (descending) and Rating (ascending):")
sorted_multi

DataFrame sorted by Votes (descending) and Rating (ascending):

  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

Zomato Business Context:

- Sorting by Total_Votes (descending) and only_rating (ascending) ranks highly engaged restaurants while resolving ties by rating, helping Zomato identify top-performing restaurants for recommendations or Zomato Gold promotions.
- This approach supports nuanced analysis, such as finding restaurants with high votes but lower ratings, which may need support from Zomato’s restaurant success team to improve customer satisfaction in Bangalore.

**Some Practice Questions**

1. Sort the DataFrame by "Rating" in descending order.
2. Find the restaurant with the highest rating after sorting.
3. Sort the DataFrame first by "Cost for Two" (ascending) and then by "Votes" (descending).
4. Create a new sorted DataFrame based on "Votes" and "Rating" and display the top 3 rows.

In [ ]:
def rearrange_image(data, num_splits):
    # 1. Split the image using np.vsplit
    sections = np.vsplit(data, num_splits)

    # 2. Rearrange sections
    modified_sections = sections[-1:] + sections[:-1]  # Cyclic shift

    # 3. Return the modified array
    return np.concatenate(modified_sections)



---