<a href="https://colab.research.google.com/github/krishik1/Backend_LLD_Sept23Morning/blob/master/pandas2_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

iloc & loc

In [ ]:
import pandas as pd
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}
df=pd.DataFrame(data)

In [ ]:
df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
#iloc:integer position based indexing
df.iloc[2:5,0:2]

  Restaurant  Votes
2         R3    150
3         R2    240
4         R4     80

In [ ]:
#loc:label/name based indexing
import pandas as pd
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

df = pd.DataFrame(data,index=["a","b","c","d","e","f"])
df

  Restaurant  Votes  Rating
a         R1    120     4.1
b         R2    240     4.5
c         R3    150     3.9
d         R2    240     4.5
e         R4     80     4.0
f         R1    120     4.1

In [ ]:
df.loc["b":"c",:"Rating"]

  Restaurant  Votes  Rating
b         R2    240     4.5
c         R3    150     3.9

In [ ]:
df.loc[df["Restaurant"]=="R1"]

  Restaurant  Votes  Rating
a         R1    120     4.1
f         R1    120     4.1

In [ ]:
df.set_index("Restaurant")#setting restuarent as index

            Votes  Rating
Restaurant
R1            120     4.1
R2            240     4.5
R3            150     3.9
R2            240     4.5
R4             80     4.0
R1            120     4.1

Duplicates

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

df = pd.DataFrame(data,index=["a","b","c","d","e","f"])
df

  Restaurant  Votes  Rating
a         R1    120     4.1
b         R2    240     4.5
c         R3    150     3.9
d         R2    240     4.5
e         R4     80     4.0
f         R1    120     4.1

In [ ]:
df.drop_duplicates() #drops the duplicate data

  Restaurant  Votes  Rating
a         R1    120     4.1
b         R2    240     4.5
c         R3    150     3.9
e         R4     80     4.0

In [ ]:
df.drop_duplicates(subset="Restaurant")

  Restaurant  Votes  Rating
a         R1    120     4.1
b         R2    240     4.5
c         R3    150     3.9
e         R4     80     4.0

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1","R1"],
    "Votes": [120, 240, 150, 240, 80, 120,230],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1,4.1]
}

df = pd.DataFrame(data,index=["a","b","c","d","e","f","g"])
df

  Restaurant  Votes  Rating
a         R1    120     4.1
b         R2    240     4.5
c         R3    150     3.9
d         R2    240     4.5
e         R4     80     4.0
f         R1    120     4.1
g         R1    230     4.1

In [ ]:
df.drop_duplicates(subset="Restaurant",keep="last",inplace=True)#keep="last" :it will give the last updated value

In [ ]:
df

  Restaurant  Votes  Rating
c         R3    150     3.9
d         R2    240     4.5
e         R4     80     4.0
g         R1    230     4.1

In [ ]:
df.drop_duplicates(subset="Restaurant",keep=False)

  Restaurant  Votes  Rating
c         R3    150     3.9
e         R4     80     4.0

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv .

--2026-07-10 14:55:34--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 13.225.41.5, 13.225.41.124, 13.225.41.45, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|13.225.41.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   143MB/s    in 0.5s

2026-07-10 14:55:35 (143 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: 'zomato_dataset.csv' and './zomato_dataset.csv' are the same file

In [ ]:
df = pd.read_csv('zomato_dataset.csv')
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

Sorting

In [ ]:
df.sort_values("votes",ascending=False)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
22531,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9 /5,16832,+91 8039514766,Sarjapur Road,Microbrewery,"Cocktails, Butter Chicken, Dahi Kebab, Rajma C...","Continental, North Indian, Italian, South Indi...",'1600.0',"[('Rated 4.0', 'RATED\n Visiting a microbrewe...",[],Drinks & nightlife,Sarjapur Road
22232,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9 /5,16832,+91 8039514766,Sarjapur Road,Microbrewery,"Cocktails, Butter Chicken, Dahi Kebab, Rajma C...","Continental, North Indian, Italian, South Indi...",'1600.0',"[('Rated 5.0', ""RATED\n This is an absolute g...",[],Delivery,Sarjapur Road
22364,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9 /5,16832,+91 8039514766,Sarjapur Road,Microbrewery,"Cocktails, Butter Chicken, Dahi Kebab, Rajma C...","Continental, North Indian, Italian, South Indi...",'1600.0',"[('Rated 4.0', 'RATED\n Visiting a microbrewe...",[],Dine-out,Sarjapur Road
1634,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9/5,16345,+91 8039514766,Sarjapur Road,Microbrewery,"Cocktails, Dahi Kebab, Rajma Chawal, Butter Ch...","Continental, North Indian, Italian, South Indi...",'1600.0',"[('Rated 5.0', 'RATED\n I have been to this p...",[],Delivery,Bellandur
1993,https://www.zomato.com/bangalore/byg-brewski-b...,"Behind MK Retail, Sarjapur Road, Bangalore",Byg Brewski Brewing Company,Yes,Yes,4.9/5,16345,+91 8039514766,Sarjapur Road,Microbrewery,"Cocktails, Dahi Kebab, Rajma Chawal, Butter Ch...","Continental, North Indian, Italian, South Indi...",'1600.0',"[('Rated 5.0', 'RATED\n I have been to this p...","['Creamy Mushroom and Truffle Soup', 'Kung Pao...",Drinks & nightlife,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4632,https://www.zomato.com/bangalore/biergarten-ko...,"4th B Cross, Koramangala 5th Block, Bangalore",Biergarten,No,Yes,NEW,0,080 49653208,Koramangala 5th Block,"Pub, Microbrewery","Beer, Mezze Platter, Penne Arrabiata Pasta, Co...","Continental, North Indian, Chinese, European, ...",'2100.0',"[('Rated 5.0', ""RATED\n Well, the place has a...",[],Dine-out,BTM
4631,https://www.zomato.com/bangalore/levitate-brew...,"57, 1st Main Rd, Sarakki Industrial Layout, 3r...",Levitate Brewery and Kitchen,No,Yes,NEW,0,080 49653113,JP Nagar,"Microbrewery, Casual Dining","Wheat Beer, Tiramisu, Lager, Rustica Pizza, Pa...","Finger Food, North Indian, Continental",'1500.0',"[('Rated 4.0', 'RATED\n Terribly expensive wi...",[],Dine-out,BTM
13722,https://www.zomato.com/bangalore/the-flying-tr...,"2, 2nd Floor, 100 Feet Road, Koramangala 5th B...",The Flying Trapeze,No,Yes,NEW,0,080 49652426,Koramangala 5th Block,Lounge,Beef Nachos,"North Indian, Continental, Chinese",'1500.0',"[('Rated 4.0', 'RATED\n This is a very new pl...",[],Dine-out,Koramangala 5th Block
23089,https://www.zomato.com/bangalore/temptation-wh...,"176, Thubarahalli, Near Kundalahalli Gate, Whi...",Temptation,Yes,No,NEW,0,+91 7406631228,Whitefield,Quick Bites,Mutton Curry,North Indian,'500.0',"[('Rated 5.0', 'RATED\n Just to say Ã\x83Ã\...",[],Dine-out,Whitefield
4644,https://www.zomato.com/bangalore/ulavacharu-ko...,"104, Vijay Jatti Building, Industrial Area, Ko...",Ulavacharu,Yes,Yes,NEW,0,080 49653538,Koramangala 5th Block,Casual Dining,"Ulavacharu, Biryani, Bangla Kodi, Rajugari Kod...","Andhra, North Indian, Chinese",'900.0',"[('Rated 5.0', 'RATED\n I had been yesterday ...","['Konaseema Kodi Vepudu', 'Boneless Kodi Chips...",Dine-out,BTM

In [ ]:
df.sort_values(["address","votes"],ascending=[True,False])

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
20492,https://www.zomato.com/bangalore/vinnys-domlur...,"# 31, 7th Cross, Opposite Canara Bank, Domlur,...",Vinny's,Yes,No,4.1 /5,367,080 41646123\n+91 9845846988,Domlur,Casual Dining,"Pizza, Pasta, Mocktails, Tiramisu, Garlic Brea...","Burger, Desserts, Italian, Pizza, Salad",'600.0',"[('Rated 3.0', 'RATED\n There are better pizz...",[],Delivery,Old Airport Road
14872,https://www.zomato.com/bangalore/vinnys-domlur...,"# 31, 7th Cross, Opposite Canara Bank, Domlur,...",Vinny's,Yes,No,4.1 /5,366,080 41646123\n+91 9845846988,Domlur,Casual Dining,"Pizza, Pasta, Mocktails, Tiramisu, Garlic Brea...","Burger, Desserts, Italian, Pizza, Salad",'600.0',"[('Rated 4.0', ""RATED\n Interesting little pl...",[],Delivery,Koramangala 6th Block
20734,https://www.zomato.com/bangalore/vinnys-domlur...,"# 31, 7th Cross, Opposite Canara Bank, Domlur,...",Vinny's,Yes,No,4.1 /5,366,080 41646123\n+91 9845846988,Domlur,Casual Dining,"Pizza, Pasta, Mocktails, Tiramisu, Garlic Brea...","Burger, Desserts, Italian, Pizza, Salad",'600.0',"[('Rated 3.0', 'RATED\n There are better pizz...",[],Dine-out,Old Airport Road
8405,https://www.zomato.com/bangalore/vinnys-domlur...,"# 31, 7th Cross, Opposite Canara Bank, Domlur,...",Vinny's,Yes,No,4.1/5,360,080 41646123\r\n+91 9845846988,Domlur,Casual Dining,"Pizza, Pasta, Mocktails, Tiramisu, Garlic Brea...","Burger, Desserts, Italian, Pizza, Salad",'600.0',"[('Rated 4.0', ""RATED\n Interesting little pl...","['Chicken Lovers Pizza', 'Brownie', '3 Egg Pla...",Dine-out,Indiranagar
7322,https://www.zomato.com/bangalore/patville-hsr?...,"#,1070 Ground Floor, 24th Main, oppiste karnat...",Patville,No,No,4.0/5,104,080 42123000,HSR,Dessert Parlor,"Tiramisu, Chocolate Pastry, Coffee, Cup Cake, ...",Desserts,'300.0',"[('Rated 5.0', 'RATED\n A small yet one of th...",[],Desserts,HSR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6304,https://www.zomato.com/bangalore/z-bar-electro...,"Zone By The Park, 26/A, Electronic City, Banga...",Z-Bar,No,Yes,4.1/5,410,+91 9513903111\r\n+91 9513903105,Electronic City,Bar,"Cocktails, Tandoori Chicken, Wine, Ice Tea, Fr...","Finger Food, North Indian",'1500.0',"[('Rated 3.0', ""RATED\n This is a rooftop res...",[],Pubs and bars,Electronic City
5989,https://www.zomato.com/bangalore/bazaar-zone-b...,"Zone by The Park, 26/A, Phase 1, Electronic Ci...",Bazaar - Zone By The Park,No,Yes,4.0/5,415,+91 9513903104\r\n+91 9513903105,Electronic City,Casual Dining,"Salads, Chicken Tikka, Roti, Gulab Jamun, Lunc...","Continental, South Indian, North Indian, Asian",'1400.0',"[('Rated 4.0', 'RATED\n Been here with family...",[],Buffet,Electronic City
6176,https://www.zomato.com/bangalore/bazaar-zone-b...,"Zone by The Park, 26/A, Phase 1, Electronic Ci...",Bazaar - Zone By The Park,No,Yes,4.0/5,415,+91 9513903104\r\n+91 9513903105,Electronic City,Casual Dining,"Salads, Chicken Tikka, Roti, Gulab Jamun, Lunc...","Continental, South Indian, North Indian, Asian",'1400.0',"[('Rated 4.0', 'RATED\n Been here with family...",[],Dine-out,Electronic City
18383,https://www.zomato.com/bangalore/artinci-artis...,"c/o Foodism, 2nd A Main Road, 445/31, 7th Cros...",Artinci Artisanal Ice Cream,Yes,No,4.2 /5,44,+91 9606706806,Marathahalli,Dessert Parlor,"Coffee, Vanilla Ice Cream, Almond Ice Cream","Desserts, Ice Cream",'300.0',"[('Rated 4.0', ""RATED\n So I have ordered and...","[""God's own Vanilla Ice cream (200ml)"", 'Dark ...",Delivery,Marathahalli
18521,https://www.zomato.com/bangalore/artinci-artis...,"c/o Foodism, 2nd A Main Road, 445/31, 7th Cros...",Artinci Artisanal Ice Cream,Yes,No,4.2 /5,44,+91 9606706806,Marathahalli,Dessert Parlor,"Coffee, Vanilla Ice Cream, Almond Ice Cream","Desserts, Ice Cream",'300.0',"[('Rated 4.0', ""RATED\n So I have ordered and...","[""God's own Vanilla Ice cream (200ml)"", 'Dark ...",Desserts,Marathahalli

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/214/original/amazon_data4.zip

--2026-07-10 18:18:28--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/214/original/amazon_data4.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.169.201.156, 3.169.201.14, 3.169.201.165, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.169.201.156|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1943535 (1.9M) [application/zip]
Saving to: ‘amazon_data4.zip’

amazon_data4.zip    100%[===================>]   1.85M  --.-KB/s    in 0.07s

2026-07-10 18:18:28 (26.3 MB/s) - ‘amazon_data4.zip’ saved [1943535/1943535]

In [ ]:
!unzip amazon_data4.zip

Archive:  amazon_data4.zip
  inflating: products.csv
  inflating: orders.csv

In [ ]:
import pandas as pd
orders = pd.read_csv('orders.csv')
orders

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000
1,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114
2,B096MSW6CT,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",2023-01-01 11:56:03.934426229
3,B08HDJ86NZ,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",2023-01-01 17:54:05.901639344
4,B08CF3B7N1,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",2023-01-01 23:52:07.868852459
...,...,...,...,...,...,...,...
1460,B08L7J3T31,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",2023-12-30 00:07:52.131147540
1461,B01M6453MB,"AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",2023-12-30 06:05:54.098360656
1462,B009P2LIL4,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",2023-12-30 12:03:56.065573772
1463,B00J5DYCCA,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,2023-12-30 18:01:58.032786884
1464,B01486F4G6,"AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,2023-12-31 00:00:00.000000000

In [ ]:
products = pd.read_csv('products.csv')
products

,product_id,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories,₹199,"₹1,899",3.9,7928.0,【 Fast Charger& Data Sync】-With built-in safet...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories,₹329,₹699,4.2,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories,₹154,₹399,4.2,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen,₹379,₹919,4.0,1090.0,SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen,"₹2,280","₹3,045",4.1,4118.0,"230 Volts, 400 watts, 1 Year",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,Home&Kitchen,"₹2,219","₹3,080",3.6,468.0,International design and styling|Two heat sett...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,Home&Kitchen,"₹1,399","₹1,890",4.0,8031.0,Fan sweep area: 230 MM ; Noise level: (40 - 45...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen,"₹2,863","₹3,690",4.3,6987.0,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

SQL Joins

In [ ]:
import pandas as pd
# Sample DataFrames
samples_orders = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003'],
    'user_id': ['U001', 'U002', 'U003'],
    'review_id': ['R001', 'R002', 'R003']
})

samples_orders

  product_id user_id review_id
0       P001    U001      R001
1       P002    U002      R002
2       P003    U003      R003

In [ ]:
samples_products = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P004'],
    'product_name': ['Product A', 'Product B', 'Product D'],
    'category': ['Category 1', 'Category 2', 'Category 3']
})
samples_products

  product_id product_name    category
0       P001    Product A  Category 1
1       P002    Product B  Category 2
2       P004    Product D  Category 3

In [ ]:
#Inner
pd.merge(samples_orders,samples_products,on="product_id",how="inner")

  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2

In [ ]:
#Left Outer
pd.merge(samples_orders,samples_products,on="product_id",how="left")

  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2
2       P003    U003      R003          NaN         NaN

In [ ]:
#Right Outer
pd.merge(samples_orders,samples_products,on="product_id",how="right")

  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2
2       P004     NaN       NaN    Product D  Category 3

In [ ]:
#Outer
pd.merge(samples_orders,samples_products,on="product_id",how="outer")

  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2
2       P003    U003      R003          NaN         NaN
3       P004     NaN       NaN    Product D  Category 3

In [ ]:
# Sample DataFrames
samples_orders = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003'],
    'user_id': ['U001', 'U002', 'U003'],
    'review_id': ['R001', 'R002', 'R003']
})

samples_products = pd.DataFrame({
    'id': ['P001', 'P002', 'P004'],
    'product_name': ['Product A', 'Product B', 'Product D'],
    'category': ['Category 1', 'Category 2', 'Category 3']
})

In [ ]:
pd.merge(samples_orders,samples_products,left_on="product_id",right_on="id",how="inner")

  product_id user_id review_id    id product_name    category
0       P001    U001      R001  P001    Product A  Category 1
1       P002    U002      R002  P002    Product B  Category 2

In [ ]:
#Apply
df=pd.merge(orders,products,on="product_id",how="left")
df.head()

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24270.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/I/51UsScvHQN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
2,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
3,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
4,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...

In [ ]:
df["review_title"].head()

0    Satisfied,Charging is really fast,Value for mo...
1    Satisfied,Charging is really fast,Value for mo...
2    Satisfied,Charging is really fast,Value for mo...
3    A Good Braided Cable for Your Type C Device,Go...
4    A Good Braided Cable for Your Type C Device,Go...
Name: review_title, dtype: object

In [ ]:
df["review_title"].apply(lambda x:x.upper())

0       SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
1       SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
2       SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
3       A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
4       A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
                              ...
1732    RECEIVED THE PRODUCT WITHOUT SPANNER,EXCELLENT...
1733    OK,EVERYTHING WAS GOOD COULDN'T RETURN BCOZ I ...
1734    VERY GOOD,WORK BUT FRONT MELT AFTER 2 MONTH,GO...
1735    FAN SPEED IS SLOW,GOOD QUALITY,GOOD PRODUCT,GO...
1736    WORKS PERFECT,OK GOOD PRODUCT,NICE PRODUCT. RE...
Name: review_title, Length: 1737, dtype: object

In [ ]:

df["discounted_price"]=df["actual_price"].apply(
    lambda x: float(str(x).replace("₹", "").replace(",", ""))
)

In [ ]:
df["discounted_price"].mean().round(2)

np.float64(4961.62)

Group By

In [ ]:
df.groupby("category")

In [ ]:
df.groupby("category").groups

{'Car&Motorbike': [1429], 'Computers&Accessories': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 34, 35, 36, 37, 38, 39, 40, 41, 42, 44, 45, 46, 47, 50, 51, 52, 57, 58, 59, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 90, 91, 92, 93, 95, 96, 97, 98, 99, 100, 101, 105, 106, 107, 108, 109, 110, 111, 112, 114, 115, 117, 119, 120, ...], 'Electronics': [32, 33, 43, 48, 49, 53, 54, 55, 56, 60, 61, 62, 63, 89, 94, 103, 104, 113, 116, 118, 123, 124, 129, 130, 131, 134, 135, 143, 155, 158, 161, 165, 166, 167, 173, 176, 178, 182, 184, 185, 190, 192, 194, 196, 198, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 217, 219, 220, 224, 226, 227, 230, 232, 234, 237, 239, 240, 241, 242, 247, 249, 250, 253, 261, 262, 270, 271, 272, 274, 275, 279, 282, 284, 285, 286, 288, 291, 292, 293, 296, 297, 298, 299, 300, 303, 304, 306, 307, 308, ...], 'Health&PersonalCare': [1519], 'Home&Kitchen': [792, 843, 1091, 1128, 1138, 1149, 1245, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1386, 1387, ...], 'HomeImprovement': [1033, 1241], 'MusicalInstruments': [786, 1027], 'OfficeProducts': [791, 824, 853, 886, 913, 942, 959, 978, 982, 986, 1003, 1017, 1036, 1039, 1055, 1084, 1085, 1096, 1106, 1117, 1135, 1166, 1199, 1201, 1203, 1207, 1227, 1259, 1269, 1271, 1272], 'Toys&Games': [1171]}

In [ ]:
df.groupby("category").get_group("MusicalInstruments")

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
786,B076B8G5D8,"AHB43CZ4RHLJ5S6CBOWX6MEI7J4Q,AF3XMPDSQQDSRN2PG...","Sameer Patil,Ashish s.,Harshal Kothari,Govinda...","R1ZSCBBOGJ8VB,R2JXWEENFMSBAQ,R1TOMRGD2ASPF,R1P...",DETAILED REVIEW with Best settings for better ...,"NOTE :@ Its ready to go Mic, which doesn't nee...",2023-06-02 09:54:05.901639344,Boya ByM1 Auxiliary Omnidirectional Lavalier C...,MusicalInstruments,1995.0,"₹1,995",4.0,68664.0,"BOYA BY-M1 is an omni directional microphone, ...",https://m.media-amazon.com/images/I/41UYenF+ln...,https://www.amazon.in/Boya-Omnidirectional-Lav...
1027,B07JF9B592,"AHQ4Q75NBEWOM4OWOXUZW7V247NQ,AEQCAMSZJTMNIKXAP...","ˢᴰ82ˢᶜ ✔️,Manish Rautela,Sai kiran,Dinesh S,Ut...","RKBKQKSEET7CC,RQM34GWJC0DPJ,R1PJNXT9PME2I1,R2V...","loud & clear,Avrage in budget range,Best for b...",at Rs.319 it's a great deal. I use it for mobi...,2023-07-18 21:46:13.770491804,MAONO AU-400 Lavalier Auxiliary Omnidirectiona...,MusicalInstruments,699.0,₹699,3.8,20218.0,4-pole jack is compatible for laptop which has...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Maono-AU-400-Lavalier-Mi...

In [ ]:
df.groupby("category")["rating"].mean().round(2)

category
Car&Motorbike            3.80
Computers&Accessories    4.16
Electronics              4.09
Health&PersonalCare      4.00
Home&Kitchen             4.05
HomeImprovement          4.25
MusicalInstruments       3.90
OfficeProducts           4.31
Toys&Games               4.30
Name: rating, dtype: float64

In [ ]:
df.groupby("category")["rating"].count()

category
Car&Motorbike              1
Computers&Accessories    638
Electronics              590
Health&PersonalCare        1
Home&Kitchen             438
HomeImprovement            2
MusicalInstruments         2
OfficeProducts            31
Toys&Games                 1
Name: rating, dtype: int64

In [ ]:
df

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24270.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/I/51UsScvHQN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
2,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
3,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,349.0,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
4,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,349.0,₹349,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1732,B08L7J3T31,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",2023-12-30 00:07:52.131147540,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen,919.0,₹919,4.0,1090.0,SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1733,B01M6453MB,"AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",2023-12-30 06:05:54.098360656,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen,3045.0,"₹3,045",4.1,4118.0,"230 Volts, 400 watts, 1 Year",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1734,B009P2LIL4,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",2023-12-30 12:03:56.065573772,Bajaj Majesty RX10 2000 Watts Heat Convector R...,Home&Kitchen,3080.0,"₹3,080",3.6,468.0,International design and styling|Two heat sett...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1735,B00J5DYCCA,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,2023-12-30 18:01:58.032786884,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,Home&Kitchen,1890.0,"₹1,890",4.0,8031.0,Fan sweep area: 230 MM ; Noise level: (40 - 45...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1736,B01486F4G6,"AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,2023-12-31 00:00:00.000000000,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen,3690.0,"₹3,690",4.3,6987.0,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [ ]:
df.groupby(["category","product_name"])["rating_count"].mean().round(2)

category               product_name
Car&Motorbike          Reffair AX30 [MAX] Portable Air Purifier for Car, Home & Office | Smart Ionizer Function | H13 Grade True HEPA Filter [Internationally Tested] Aromabuds Fragrance Option - Black                          1118.0
Computers&Accessories  APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS System, an Ideal Power Backup & Protection for Home Office, Desktop PC & Home Electronics                                                                  15783.0
                       Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x1080) VA Panel LCD Monitor with LED Back Light I 250 Nits I HDMI, VGA Ports I Eye Care Features Like Bluelight Shield, Flickerless & Comfy View (Black)     2014.0
                       Agaro Blaze USBA to micro +Type C 2in1 Braided 1.2M Cable                                                                                                                                                 14184.0
                       AirCase Protective Laptop Bag Sleeve fits Upto 13.3" Laptop/ MacBook, Wrinkle Free, Padded, Waterproof Light Neoprene case Cover Pouch, for Men & Women, Black- 6 Months Warranty                          9940.0
                                                                                                                                                                                                                                  ...
OfficeProducts         Pentonic Multicolor Ball Point Pen, Pack of 10                                                                                                                                                             4308.0
                       Pilot Frixion Clicker Roller Pen (Blue), (9000019529)                                                                                                                                                      6199.0
                       Pilot V7 Liquid Ink Roller Ball Pen (2 Blue + 1 Black)                                                                                                                                                     2450.0
                       Portronics Ruffpad 15 Re-Writable LCD Screen 38.1cm (15-inch) Writing Pad for Drawing, Playing, Handwriting Gifts for Kids & Adults (Grey)                                                                 3530.0
Toys&Games             Faber-Castell Connector Pen Set - Pack of 25 (Assorted)                                                                                                                                                   15867.0
Name: rating_count, Length: 1330, dtype: float64

In [ ]:
df.groupby(["category","product_name"])["rating_count"].agg(["min","max","mean"])

                                                                              min  \
category              product_name
Car&Motorbike         Reffair AX30 [MAX] Portable Air Purifier for Ca...   1118.0
Computers&Accessories APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS ...  15783.0
                      Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x...   2014.0
                      Agaro Blaze USBA to micro +Type C 2in1 Braided ...  14184.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9940.0
...                                                                           ...
OfficeProducts        Pentonic Multicolor Ball Point Pen, Pack of 10       4308.0
                      Pilot Frixion Clicker Roller Pen (Blue), (90000...   6199.0
                      Pilot V7 Liquid Ink Roller Ball Pen (2 Blue + 1...   2450.0
                      Portronics Ruffpad 15 Re-Writable LCD Screen 38...   3530.0
Toys&Games            Faber-Castell Connector Pen Set - Pack of 25 (A...  15867.0

                                                                              max  \
category              product_name
Car&Motorbike         Reffair AX30 [MAX] Portable Air Purifier for Ca...   1118.0
Computers&Accessories APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS ...  15783.0
                      Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x...   2014.0
                      Agaro Blaze USBA to micro +Type C 2in1 Braided ...  14184.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9940.0
...                                                                           ...
OfficeProducts        Pentonic Multicolor Ball Point Pen, Pack of 10       4308.0
                      Pilot Frixion Clicker Roller Pen (Blue), (90000...   6199.0
                      Pilot V7 Liquid Ink Roller Ball Pen (2 Blue + 1...   2450.0
                      Portronics Ruffpad 15 Re-Writable LCD Screen 38...   3530.0
Toys&Games            Faber-Castell Connector Pen Set - Pack of 25 (A...  15867.0

                                                                             mean
category              product_name
Car&Motorbike         Reffair AX30 [MAX] Portable Air Purifier for Ca...   1118.0
Computers&Accessories APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS ...  15783.0
                      Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x...   2014.0
                      Agaro Blaze USBA to micro +Type C 2in1 Braided ...  14184.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9940.0
...                                                                           ...
OfficeProducts        Pentonic Multicolor Ball Point Pen, Pack of 10       4308.0
                      Pilot Frixion Clicker Roller Pen (Blue), (90000...   6199.0
                      Pilot V7 Liquid Ink Roller Ball Pen (2 Blue + 1...   2450.0
                      Portronics Ruffpad 15 Re-Writable LCD Screen 38...   3530.0
Toys&Games            Faber-Castell Connector Pen Set - Pack of 25 (A...  15867.0

[1330 rows x 3 columns]

In [ ]:
fil=df.groupby('category')['rating'].mean()

category
Car&Motorbike            3.800000
Computers&Accessories    4.158934
Electronics              4.090508
Health&PersonalCare      4.000000
Home&Kitchen             4.045890
HomeImprovement          4.250000
MusicalInstruments       3.900000
OfficeProducts           4.309677
Toys&Games               4.300000
Name: rating, dtype: float64

In [ ]:
df.groupby('category').filter(
    lambda x:x['rating'].mean()>=4
).head()

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24270.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/I/51UsScvHQN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
2,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,1099.0,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
3,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,349.0,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
4,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,349.0,₹349,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...